---
title: "Figure 1"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load the libraries
library(tidyverse)
library(readr)
library(here)
library(psych)
library(english)
library(stringr)
library(tableone)
library(kableExtra)
library(scales)
library(ggridges)
library(plotly)
library(patchwork)
library(haven)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
```

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
# Read in the clean csv file
leger <- read_csv("data/leger_for_analyses.csv")

# subset for chronic people only
leger_chronic <- leger %>%
  filter(chronic_dummy == 1)
```


```{r echo=FALSE, warning=FALSE, fig.width=12, fig.height=18}

vaxed <- leger_chronic %>%
  filter(vaccine_dummy == 1) %>%
  mutate_at(vars(c(inf1:inf16)),
            funs(case_when(. == 1 ~ 1,
                           . == 2 | . == 3 | . == 4 ~ 0))) %>%
  pivot_longer(names_to = "influence", values_to = "value", cols = c(inf1:inf16)) %>%
  group_by(influence, value) %>%
  count(influence) %>%
  drop_na() %>%
  ungroup(influence, value) %>%
  filter(value == 1) %>%
  select(-value) %>%
  mutate(influence = as.factor(influence),
         influence = fct_reorder(influence, n)) %>%
  ggplot(aes(x = n, y = influence, fill = influence)) +
  geom_col() +
  geom_text(aes(label = paste0(round((n/2294*100),1),"%"), x = n - 70)) +
  labs(title = "Motivations among vaccinated individuals (N = 2,294)",
       x = "Number of people responding 'To a great extent'",
       y = " ") +
  theme_classic(base_size = 16) +
  theme(legend.position = "none",
        strip.text = element_text(face = 'bold'),
        panel.grid.major.x = element_line()) +
  scale_y_discrete(breaks = c("inf1", "inf2", "inf3", "inf4", "inf5", "inf6", "inf7", "inf10",
                              "inf11", "inf12", "inf13", "inf14", "inf15", "inf16", "inf17", "inf18"),
                   labels = c("Trust in vaccine company",
                              "Info of no side effects",
                              "Info about effectiveness",
                              "Personal high risk",
                              "Other's positive att.",
                              "Others getting vaccine",
                              "Doctor recommendation",
                              "Convenience of getting vaccine",
                              "Protect others",
                              "Attending events",
                              "Doing my part",
                              "Employer recommendation",
                              "Only need 1 dose",
                              "Reduce my worries",
                              "Effective for variants",
                              "Vaccine of choice")) +
  scale_fill_viridis_d(alpha = 0.9,
                       begin = 0.3, end = 1)

unvaxed_3 <- leger_chronic %>%
  filter(vaccine_dummy == 0) %>%
  mutate_at(vars(c(inf1:inf16)), 
            funs(case_when(. == 1 ~ 1,
                           . == 2 | . == 3 | . == 4 ~ 0))) %>%
  pivot_longer(names_to = "influence", values_to = "value", cols = c(inf1:inf16)) %>%
  group_by(influence, value) %>%
  count(influence) %>%
  drop_na() %>%
  ungroup(influence, value) %>%
  filter(value == 1) %>%
  select(-value)%>%
  mutate(prop = n/251*100) %>%
  mutate(prop = round(prop, 1)) %>%
  mutate(influence = as.factor(influence),
         influence = fct_reorder(influence, prop)) %>%
  ggplot(aes(x = prop, y = influence, fill = influence)) + 
  geom_col() + 
  geom_text(aes(label = paste0(prop,"%"), x = prop-3)) +
  labs(title = "Motivations among unvaccinated individuals (N = 251)", 
       x = "Proportion of people responding 'To a great extent'",
       y = " ") + 
  xlim(0, 100) +
  theme_classic(base_size = 16) +
  theme(legend.position = "none",
        strip.text = element_text(face = 'bold'),
        panel.grid.major.x = element_line()) +
  scale_y_discrete(breaks = c("inf1", "inf2", "inf3", "inf4", "inf5", "inf6", "inf7", "inf10",
                              "inf11", "inf12", "inf13", "inf14", "inf15", "inf16", "inf17", "inf18"),
                   labels = c("Trust in vaccine company",
                              "Info of no side effects",
                              "Info about effectiveness",
                              "Personal high risk",
                              "Other's positive att.",
                              "Others getting vaccine",
                              "Doctor recommendation",
                              "Convenience of getting vaccine",
                              "Protect others",
                              "Attending events",
                              "Doing my part",
                              "Employer recommendation",
                              "Only need 1 dose",
                              "Reduce my worries",
                              "Effective for variants",
                              "Vaccine of choice")) +
  scale_fill_viridis_d(alpha = 0.9,
                       begin = 0.3, end = 1)

(vaxed/unvaxed_3) + plot_annotation(tag_levels = 'A')
```

