---
title: "Project log"
author: "Prepared by UK"
date: "First opened: 2021-11-17 | Last update: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###  
**Nov 10 -12, 2021**

Project conceptualization: Upon my work for the infographics for the website, I decided to explore the vaccine uptake and motivations about vaccination in Canadian adults with physical chronic health conditions - those most at risk during the pandemic. I decide to focus on the data collected in the last 2 survey waves (June and September) as that's when vaccine was already widely available in Canada, with 75% of the population fully vaccinated against COVID-19 ([Oxford Data](https://ourworldindata.org/covid-vaccinations)).

**Monday, November 15, 2021**

Draft of the research letter sent to the colleagues: JS, KJD, TBP, and the PIs of the study: SB and KL. Feedback on the overall idea and vaccine framing requested.

**Wednesday, November 17, 2021**

Project stalls due to internal processes. Initial feedback from KJD, TBP is positive.

**Monday, November 22, 2021**

Received feedback from KL, revised the manuscript, added relevant reference and sent back to review to the primary team.
The main 3 remaining questions are: 

* How to cut the word count to have it under 600 words?
* Should be assess the associations with the vaccine using Logistic regression and report ORs, or just simplify with bivariate associations?
* Currently, the grouping of province is collating BC, Alberta, Manitoba and Saskachewan - perhaps this should be separated, given that we know there exist differences.

**Tuesday, November 30, 2021**

Reworked the main text of the manuscript and added a sub-table to divide individuals with chronic health conditions based on their vaccination status.
We decided to simplify the analyses and removed logistic regression. Instead we only used the table and include the bivariate comparisons between the sample with chronic health conditions
Additionally, I reworked the main figure in order to include % rather than N on x axis.
The 3rd draft sent out for revision.

**Monday, December 6, 2021**

Looking at feedback from SLB, need will incorporate a few comments and start formatting for journal.

**Tuesday, December 7, 2021**

Incorporated final feedback and made text more concise. Added a further break down to the figure - fully vaccinated, partially vaccinated, non-vaccinated.
Manually fixed the table and proportions in it. Summarized the changes and added funding, COI statement and sent back to co-authors, waiting for feedback by Friday for submission.
